/**
 * Dizionario ticker → nome completo, usato per la ricerca locale per nome.
 * Copre la maggior parte dei 1024 ticker del sistema. I ticker non presenti
 * qui restano cercabili solo per simbolo esatto.
 */

export const TICKER_NAMES: Record<string, string> = {
  // === S&P 500 Big Tech ===
  AAPL: 'Apple Inc.',
  MSFT: 'Microsoft Corporation',
  GOOGL: 'Alphabet Inc. (Google) Class A',
  GOOG: 'Alphabet Inc. (Google) Class C',
  AMZN: 'Amazon.com Inc.',
  META: 'Meta Platforms Inc. (Facebook)',
  NVDA: 'NVIDIA Corporation',
  TSLA: 'Tesla Inc.',
  ORCL: 'Oracle Corporation',
  ADBE: 'Adobe Inc.',
  CRM: 'Salesforce Inc.',
  AMD: 'Advanced Micro Devices',
  INTC: 'Intel Corporation',
  CSCO: 'Cisco Systems Inc.',
  QCOM: 'Qualcomm Inc.',
  TXN: 'Texas Instruments',
  IBM: 'IBM Corporation',
  NOW: 'ServiceNow Inc.',
  INTU: 'Intuit Inc.',
  ACN: 'Accenture plc',
  PYPL: 'PayPal Holdings',
  UBER: 'Uber Technologies',
  SHOP: 'Shopify Inc.',
  ADI: 'Analog Devices',
  MU: 'Micron Technology',
  LRCX: 'Lam Research',
  KLAC: 'KLA Corporation',
  AMAT: 'Applied Materials',
  SNPS: 'Synopsys Inc.',
  CDNS: 'Cadence Design Systems',
  MRVL: 'Marvell Technology',
  PANW: 'Palo Alto Networks',
  FTNT: 'Fortinet Inc.',
  CRWD: 'CrowdStrike Holdings',
  ANET: 'Arista Networks',
  WDAY: 'Workday Inc.',
  TEAM: 'Atlassian Corporation',
  DDOG: 'Datadog Inc.',
  NET: 'Cloudflare Inc.',
  SNOW: 'Snowflake Inc.',
  ZS: 'Zscaler Inc.',
  OKTA: 'Okta Inc.',
  SPLK: 'Splunk Inc.',
  DOCU: 'DocuSign Inc.',
  ZM: 'Zoom Video Communications',
  TWLO: 'Twilio Inc.',
  ROKU: 'Roku Inc.',
  PINS: 'Pinterest Inc.',

  // Finance
  JPM: 'JPMorgan Chase & Co.',
  'BRK-B': 'Berkshire Hathaway Class B',
  V: 'Visa Inc.',
  MA: 'Mastercard Inc.',
  BAC: 'Bank of America',
  WFC: 'Wells Fargo & Co.',
  GS: 'Goldman Sachs',
  MS: 'Morgan Stanley',
  C: 'Citigroup Inc.',
  AXP: 'American Express',
  BLK: 'BlackRock Inc.',
  SCHW: 'Charles Schwab',
  USB: 'U.S. Bancorp',
  PNC: 'PNC Financial',
  TFC: 'Truist Financial',
  COF: 'Capital One Financial',
  BK: 'Bank of New York Mellon',
  MET: 'MetLife Inc.',
  AIG: 'American International Group',
  PRU: 'Prudential Financial',
  ALL: 'The Allstate Corporation',
  TRV: 'Travelers Companies',
  AFL: 'Aflac Inc.',
  CB: 'Chubb Limited',
  PGR: 'Progressive Corporation',
  HIG: 'Hartford Financial Services',
  CME: 'CME Group',
  ICE: 'Intercontinental Exchange',
  SPGI: 'S&P Global Inc.',
  MCO: "Moody's Corporation",
  MSCI: 'MSCI Inc.',
  NDAQ: 'Nasdaq Inc.',

  // Healthcare
  JNJ: 'Johnson & Johnson',
  UNH: 'UnitedHealth Group',
  LLY: 'Eli Lilly and Company',
  ABBV: 'AbbVie Inc.',
  MRK: 'Merck & Co.',
  PFE: 'Pfizer Inc.',
  TMO: 'Thermo Fisher Scientific',
  ABT: 'Abbott Laboratories',
  DHR: 'Danaher Corporation',
  BMY: 'Bristol-Myers Squibb',
  AMGN: 'Amgen Inc.',
  MDT: 'Medtronic plc',
  ELV: 'Elevance Health',
  GILD: 'Gilead Sciences',
  ISRG: 'Intuitive Surgical',
  CVS: 'CVS Health',
  HUM: 'Humana Inc.',
  CI: 'The Cigna Group',
  VRTX: 'Vertex Pharmaceuticals',
  REGN: 'Regeneron Pharmaceuticals',
  BSX: 'Boston Scientific',
  SYK: 'Stryker Corporation',
  ZTS: 'Zoetis Inc.',
  BDX: 'Becton Dickinson',
  EW: 'Edwards Lifesciences',
  HCA: 'HCA Healthcare',
  BIIB: 'Biogen Inc.',

  // Consumer
  WMT: 'Walmart Inc.',
  PG: 'Procter & Gamble',
  HD: 'The Home Depot',
  COST: 'Costco Wholesale',
  KO: 'The Coca-Cola Company',
  PEP: 'PepsiCo Inc.',
  MCD: "McDonald's Corporation",
  NKE: 'Nike Inc.',
  DIS: 'The Walt Disney Company',
  LOW: "Lowe's Companies",
  SBUX: 'Starbucks Corporation',
  TGT: 'Target Corporation',
  CL: 'Colgate-Palmolive',
  MDLZ: 'Mondelez International',
  MO: 'Altria Group',
  PM: 'Philip Morris International',
  EL: 'Estée Lauder Companies',
  KMB: 'Kimberly-Clark',
  GIS: 'General Mills',
  K: 'Kellanova (Kellogg)',
  HSY: 'The Hershey Company',
  CLX: 'The Clorox Company',
  CHD: 'Church & Dwight',
  MKC: 'McCormick & Company',
  STZ: 'Constellation Brands',
  KHC: 'Kraft Heinz',
  TSN: 'Tyson Foods',
  KR: 'The Kroger Co.',
  BKNG: 'Booking Holdings',
  ABNB: 'Airbnb Inc.',
  MAR: 'Marriott International',
  HLT: 'Hilton Worldwide',
  MGM: 'MGM Resorts International',
  CCL: 'Carnival Corporation',
  RCL: 'Royal Caribbean Cruises',
  YUM: 'Yum! Brands',
  CMG: 'Chipotle Mexican Grill',
  DPZ: "Domino's Pizza",
  ULTA: 'Ulta Beauty',
  BBY: 'Best Buy',
  TJX: 'The TJX Companies',
  ROST: 'Ross Stores',
  LULU: 'Lululemon Athletica',
  DECK: 'Deckers Outdoor',
  RL: 'Ralph Lauren',
  TPR: 'Tapestry Inc.',
  HAS: 'Hasbro Inc.',
  MAT: 'Mattel Inc.',
  NFLX: 'Netflix Inc.',
  EA: 'Electronic Arts',
  TTWO: 'Take-Two Interactive',

  // Industrials
  BA: 'The Boeing Company',
  CAT: 'Caterpillar Inc.',
  HON: 'Honeywell International',
  UPS: 'United Parcel Service',
  RTX: 'RTX Corporation',
  LMT: 'Lockheed Martin',
  GE: 'General Electric',
  MMM: '3M Company',
  DE: 'Deere & Company',
  EMR: 'Emerson Electric',
  ITW: 'Illinois Tool Works',
  ETN: 'Eaton Corporation',
  CMI: 'Cummins Inc.',
  FDX: 'FedEx Corporation',
  NOC: 'Northrop Grumman',
  GD: 'General Dynamics',
  CSX: 'CSX Corporation',
  UNP: 'Union Pacific',
  NSC: 'Norfolk Southern',
  LUV: 'Southwest Airlines',
  DAL: 'Delta Air Lines',
  UAL: 'United Airlines Holdings',

  // Energy
  XOM: 'Exxon Mobil Corporation',
  CVX: 'Chevron Corporation',
  COP: 'ConocoPhillips',
  EOG: 'EOG Resources',
  MPC: 'Marathon Petroleum',
  PSX: 'Phillips 66',
  VLO: 'Valero Energy',
  OXY: 'Occidental Petroleum',
  SLB: 'Schlumberger',
  HAL: 'Halliburton Company',

  // Utilities
  NEE: 'NextEra Energy',
  DUK: 'Duke Energy',
  SO: 'The Southern Company',
  D: 'Dominion Energy',
  AEP: 'American Electric Power',

  // Telecom
  T: 'AT&T Inc.',
  VZ: 'Verizon Communications',
  CMCSA: 'Comcast Corporation',
  TMUS: 'T-Mobile US',
  CHTR: 'Charter Communications',

  // REITs
  PLD: 'Prologis Inc.',
  AMT: 'American Tower',
  EQIX: 'Equinix Inc.',
  CCI: 'Crown Castle',
  SPG: 'Simon Property Group',
  O: 'Realty Income',

  // Materials
  LIN: 'Linde plc',
  SHW: 'Sherwin-Williams',
  NEM: 'Newmont Corporation',
  FCX: 'Freeport-McMoRan',

  // NASDAQ only
  AVGO: 'Broadcom Inc.',
  ASML: 'ASML Holding N.V.',
  MELI: 'MercadoLibre Inc.',
  NXPI: 'NXP Semiconductors',
  MCHP: 'Microchip Technology',
  KDP: 'Keurig Dr Pepper',
  ON: 'ON Semiconductor',
  CDW: 'CDW Corporation',
  VRSK: 'Verisk Analytics',
  SIRI: 'Sirius XM Holdings',
  ALGN: 'Align Technology',
  SMCI: 'Super Micro Computer',
  ARM: 'Arm Holdings',
  MDB: 'MongoDB Inc.',
  HOOD: 'Robinhood Markets',
  COIN: 'Coinbase Global',
  RIVN: 'Rivian Automotive',
  LCID: 'Lucid Group',
  PLTR: 'Palantir Technologies',
  SOFI: 'SoFi Technologies',
  AFRM: 'Affirm Holdings',
  UPST: 'Upstart Holdings',
  DKNG: 'DraftKings Inc.',
  PENN: 'Penn Entertainment',
  ETSY: 'Etsy Inc.',
  CHWY: 'Chewy Inc.',
  EBAY: 'eBay Inc.',
  SNAP: 'Snap Inc.',
  SPOT: 'Spotify Technology',
  RBLX: 'Roblox Corporation',
  DASH: 'DoorDash Inc.',
  HUBS: 'HubSpot Inc.',
  ILMN: 'Illumina Inc.',
  TTD: 'The Trade Desk',
  DLTR: 'Dollar Tree Inc.',
  DXCM: 'DexCom Inc.',

  // === Crypto ===
  'BTC-USD': 'Bitcoin',
  'ETH-USD': 'Ethereum',
  'BNB-USD': 'BNB (Binance Coin)',
  'SOL-USD': 'Solana',
  'XRP-USD': 'XRP (Ripple)',
  'ADA-USD': 'Cardano',
  'DOGE-USD': 'Dogecoin',
  'AVAX-USD': 'Avalanche',
  'DOT-USD': 'Polkadot',
  'MATIC-USD': 'Polygon',
  'LINK-USD': 'Chainlink',
  'TRX-USD': 'TRON',
  'LTC-USD': 'Litecoin',
  'ATOM-USD': 'Cosmos',
  'ETC-USD': 'Ethereum Classic',
  'XLM-USD': 'Stellar',
  'NEAR-USD': 'NEAR Protocol',
  'FIL-USD': 'Filecoin',
  'ICP-USD': 'Internet Computer',
  'APT-USD': 'Aptos',
  'ARB-USD': 'Arbitrum',
  'HBAR-USD': 'Hedera',
  'VET-USD': 'VeChain',
  'ALGO-USD': 'Algorand',
  'MANA-USD': 'Decentraland',
  'SAND-USD': 'The Sandbox',
  'AXS-USD': 'Axie Infinity',
  'AAVE-USD': 'Aave',
  'MKR-USD': 'Maker',
  'COMP-USD': 'Compound',
  'SNX-USD': 'Synthetix',
  'CRV-USD': 'Curve DAO',
  'SUSHI-USD': 'SushiSwap',
  'LDO-USD': 'Lido DAO',
  'GRT-USD': 'The Graph',
  'SHIB-USD': 'Shiba Inu',
  'RNDR-USD': 'Render Token',
  'FET-USD': 'Fetch.ai',
  'INJ-USD': 'Injective',
  'TIA-USD': 'Celestia',
  'SEI-USD': 'Sei Network',
  'OP-USD': 'Optimism',
  'STX-USD': 'Stacks',
  'KAS-USD': 'Kaspa',
  'XMR-USD': 'Monero',
  'BCH-USD': 'Bitcoin Cash',
  'THETA-USD': 'Theta Network',
  'EOS-USD': 'EOS',
  'XTZ-USD': 'Tezos',
  'NEO-USD': 'NEO',
  'ZEC-USD': 'Zcash',
  'FTM-USD': 'Fantom',
  'EGLD-USD': 'MultiversX (Elrond)',
  'FLOW-USD': 'Flow',

  // === Italia ===
  'ENI.MI': 'Eni S.p.A.',
  'ISP.MI': 'Intesa Sanpaolo',
  'UCG.MI': 'UniCredit',
  'ENEL.MI': 'Enel S.p.A.',
  'STM.MI': 'STMicroelectronics',
  'TIT.MI': 'Telecom Italia',
  'G.MI': 'Assicurazioni Generali',
  'RACE.MI': 'Ferrari N.V.',
  'MB.MI': 'Mediobanca',
  'LUX.MI': 'Luxottica Group',
  'CNHI.MI': 'CNH Industrial',
  'MONC.MI': 'Moncler',
  'PRY.MI': 'Prysmian Group',
  'AMP.MI': 'Amplifon',
  'A2A.MI': 'A2A S.p.A.',
  'ATL.MI': 'Atlantia',
  'BAMI.MI': 'Banco BPM',
  'BMPS.MI': 'Banca Monte dei Paschi di Siena',
  'CPR.MI': 'Davide Campari-Milano',
  'ERG.MI': 'ERG S.p.A.',
  'IP.MI': 'Interpump Group',
  'JUVE.MI': 'Juventus FC',
  'LDO.MI': 'Leonardo S.p.A.',
  'NEXI.MI': 'Nexi S.p.A.',
  'PIRC.MI': 'Pirelli & C.',
  'PST.MI': 'Poste Italiane',
  'SPM.MI': 'Saipem',
  'SRG.MI': 'Snam S.p.A.',
  'STLAM.MI': 'Stellantis',
  'TEN.MI': 'Tenaris',
  'TRN.MI': 'Terna',
  'UNI.MI': 'Unipol Gruppo',

  // === Francia ===
  'SAN.PA': 'Sanofi',
  'AIR.PA': 'Airbus SE',
  'MC.PA': 'LVMH Moët Hennessy Louis Vuitton',
  'OR.PA': "L'Oréal",
  'BNP.PA': 'BNP Paribas',
  'KER.PA': 'Kering (Gucci)',
  'CAP.PA': 'Capgemini',
  'SU.PA': 'Schneider Electric',
  'ORA.PA': 'Orange S.A.',
  'RI.PA': 'Pernod Ricard',
  'AI.PA': 'Air Liquide',
  'BN.PA': 'Danone',
  'CS.PA': 'AXA',
  'EL.PA': 'EssilorLuxottica',
  'HO.PA': 'Thales',
  'RMS.PA': 'Hermès International',
  'RNO.PA': 'Renault',
  'SAF.PA': 'Safran',
  'TTE.PA': 'TotalEnergies',
  'VIE.PA': 'Veolia Environnement',
  'VIV.PA': 'Vivendi',

  // === Germania ===
  'SAP.DE': 'SAP SE',
  'SIE.DE': 'Siemens AG',
  'BAS.DE': 'BASF SE',
  'ALV.DE': 'Allianz SE',
  'BMW.DE': 'Bayerische Motoren Werke (BMW)',
  'VOW3.DE': 'Volkswagen AG',
  'DTE.DE': 'Deutsche Telekom',
  'DBK.DE': 'Deutsche Bank',
  'ADS.DE': 'Adidas AG',
  'IFX.DE': 'Infineon Technologies',
  'MRK.DE': 'Merck KGaA',
  'LIN.DE': 'Linde plc',
  'MUV2.DE': 'Münchener Rückversicherung',
  'HEN3.DE': 'Henkel AG',
  'BEI.DE': 'Beiersdorf AG',
  'CON.DE': 'Continental AG',
  'DB1.DE': 'Deutsche Börse',
  'DHL.DE': 'Deutsche Post (DHL)',
  'EOAN.DE': 'E.ON SE',
  'MBG.DE': 'Mercedes-Benz Group',
  'P911.DE': 'Dr. Ing. h.c. F. Porsche AG',
  'PUM.DE': 'Puma SE',
  'RWE.DE': 'RWE AG',
  'ZAL.DE': 'Zalando SE',

  // === UK ===
  'ULVR.L': 'Unilever plc',
  'SHEL.L': 'Shell plc',
  'HSBA.L': 'HSBC Holdings',
  'AZN.L': 'AstraZeneca plc',
  'BP.L': 'BP plc',
  'GSK.L': 'GSK plc (GlaxoSmithKline)',
  'RIO.L': 'Rio Tinto plc',
  'DGE.L': 'Diageo plc',
  'BHP.L': 'BHP Group',
  'GLEN.L': 'Glencore plc',
  'VOD.L': 'Vodafone Group',
  'LLOY.L': 'Lloyds Banking Group',
  'BARC.L': 'Barclays plc',
  'NWG.L': 'NatWest Group',
  'STAN.L': 'Standard Chartered',
  'PRU.L': 'Prudential plc',
  'LGEN.L': 'Legal & General',
  'AV.L': 'Aviva plc',
  'REL.L': 'RELX plc',
  'TSCO.L': 'Tesco plc',
  'BATS.L': 'British American Tobacco',
  'IHG.L': 'InterContinental Hotels Group',
  'LSEG.L': 'London Stock Exchange Group',

  // === Olanda ===
  'ASML.AS': 'ASML Holding N.V.',
  'ADYEN.AS': 'Adyen N.V.',
  'HEIA.AS': 'Heineken N.V.',
  'INGA.AS': 'ING Groep',
  'PHIA.AS': 'Koninklijke Philips',
  'AD.AS': 'Ahold Delhaize',
  'UNA.AS': 'Unilever N.V.',
  'ABN.AS': 'ABN AMRO',
  'KPN.AS': 'Koninklijke KPN',

  // === Spagna ===
  'ITX.MC': 'Inditex (Zara)',
  'IBE.MC': 'Iberdrola',
  'SAN.MC': 'Banco Santander',
  'BBVA.MC': 'Banco Bilbao Vizcaya Argentaria',
  'TEF.MC': 'Telefónica',
  'REP.MC': 'Repsol',
  'FER.MC': 'Ferrovial',
  'AMS.MC': 'Amadeus IT Group',

  // === Svizzera ===
  'NESN.SW': 'Nestlé S.A.',
  'ROG.SW': 'Roche Holding',
  'NOVN.SW': 'Novartis AG',
  'UBSG.SW': 'UBS Group',
  'ZURN.SW': 'Zurich Insurance Group',
  'ABBN.SW': 'ABB Ltd',
  'CFR.SW': 'Compagnie Financière Richemont',
  'GIVN.SW': 'Givaudan SA',
  'SIKA.SW': 'Sika AG',
  'LONN.SW': 'Lonza Group',

  // === Giappone ===
  '7203.T': 'Toyota Motor Corporation',
  '6758.T': 'Sony Group',
  '6861.T': 'Keyence Corporation',
  '8306.T': 'Mitsubishi UFJ Financial',
  '9432.T': 'Nippon Telegraph and Telephone (NTT)',
  '9433.T': 'KDDI Corporation',
  '9434.T': 'SoftBank Corp.',
  '9984.T': 'SoftBank Group',
  '6098.T': 'Recruit Holdings',
  '8035.T': 'Tokyo Electron',
  '6501.T': 'Hitachi Ltd.',
  '6502.T': 'Toshiba Corporation',
  '6503.T': 'Mitsubishi Electric',
  '6954.T': 'Fanuc Corporation',
  '6902.T': 'Denso Corporation',
  '7267.T': 'Honda Motor',
  '7201.T': 'Nissan Motor',
  '7974.T': 'Nintendo Co.',
  '4502.T': 'Takeda Pharmaceutical',
  '4503.T': 'Astellas Pharma',
  '4568.T': 'Daiichi Sankyo',
  '8316.T': 'Sumitomo Mitsui Financial',
  '8411.T': 'Mizuho Financial',
  '8058.T': 'Mitsubishi Corporation',
  '8031.T': 'Mitsui & Co.',
  '8001.T': 'Itochu Corporation',
  '9020.T': 'East Japan Railway',
  '9983.T': 'Fast Retailing (Uniqlo)',
  '4661.T': 'Oriental Land (Tokyo Disneyland)',
  '6752.T': 'Panasonic Holdings',
  '7751.T': 'Canon Inc.',
  '6971.T': 'Kyocera Corporation',

  // === Forex ===
  'EURUSD=X': 'Euro / US Dollar',
  'GBPUSD=X': 'British Pound / US Dollar',
  'USDJPY=X': 'US Dollar / Japanese Yen',
  'USDCHF=X': 'US Dollar / Swiss Franc',
  'AUDUSD=X': 'Australian Dollar / US Dollar',
  'USDCAD=X': 'US Dollar / Canadian Dollar',
  'NZDUSD=X': 'New Zealand Dollar / US Dollar',
  'EURGBP=X': 'Euro / British Pound',

  // === Commodities ===
  'GC=F': 'Gold Futures',
  'SI=F': 'Silver Futures',
  'PL=F': 'Platinum Futures',
  'PA=F': 'Palladium Futures',
  'HG=F': 'Copper Futures',
  'CL=F': 'Crude Oil WTI Futures',
  'BZ=F': 'Brent Crude Oil Futures',
  'NG=F': 'Natural Gas Futures',
  'ZC=F': 'Corn Futures',
  'ZS=F': 'Soybean Futures',
  'ZW=F': 'Wheat Futures',
  'KC=F': 'Coffee Futures',
  'CC=F': 'Cocoa Futures',
  'SB=F': 'Sugar Futures',
  'CT=F': 'Cotton Futures',
  GLD: 'SPDR Gold Shares',
  SLV: 'iShares Silver Trust',
  USO: 'United States Oil Fund',
  UNG: 'United States Natural Gas Fund',
  GDX: 'VanEck Gold Miners ETF',
  URA: 'Global X Uranium ETF',
  LIT: 'Global X Lithium & Battery Tech',

  // === ETF principali ===
  SPY: 'SPDR S&P 500 ETF Trust',
  QQQ: 'Invesco QQQ Trust (NASDAQ-100)',
  IWM: 'iShares Russell 2000 ETF',
  DIA: 'SPDR Dow Jones Industrial Average',
  VTI: 'Vanguard Total Stock Market ETF',
  VOO: 'Vanguard S&P 500 ETF',
  IVV: 'iShares Core S&P 500 ETF',
  VEA: 'Vanguard FTSE Developed Markets',
  VWO: 'Vanguard FTSE Emerging Markets',
  EFA: 'iShares MSCI EAFE ETF',
  EEM: 'iShares MSCI Emerging Markets',
  XLK: 'Technology Select Sector SPDR',
  XLF: 'Financial Select Sector SPDR',
  XLE: 'Energy Select Sector SPDR',
  XLV: 'Health Care Select Sector SPDR',
  XLI: 'Industrial Select Sector SPDR',
  XLP: 'Consumer Staples Select Sector SPDR',
  XLY: 'Consumer Discretionary Select Sector SPDR',
  XLU: 'Utilities Select Sector SPDR',
  ARKK: 'ARK Innovation ETF',
  ARKG: 'ARK Genomic Revolution ETF',
  SMH: 'VanEck Semiconductor ETF',
  SOXX: 'iShares Semiconductor ETF',
  TLT: 'iShares 20+ Year Treasury Bond',
  AGG: 'iShares Core U.S. Aggregate Bond',
  BND: 'Vanguard Total Bond Market',
  TQQQ: 'ProShares UltraPro QQQ (3x)',
  SQQQ: 'ProShares UltraPro Short QQQ (-3x)',
  VXX: 'iPath Series B S&P 500 VIX',
};

/**
 * Cerca ticker o nome. Case-insensitive.
 * Matching priority:
 *   1. Match esatto sul ticker (più rilevante)
 *   2. Inizio del ticker (es. "APP" → "APPL...")
 *   3. Inizio del nome (es. "Apple" → "AAPL")
 *   4. Substring nel nome
 *   5. Substring nel ticker
 */
export type LocalSearchResult = {
  ticker: string;
  name: string;
  score: number;
};

export function localSearch(
  query: string,
  allTickers: readonly string[],
  limit = 10
): LocalSearchResult[] {
  const q = query.trim().toUpperCase();
  if (q.length === 0) return [];

  const results: LocalSearchResult[] = [];
  for (const ticker of allTickers) {
    const upper = ticker.toUpperCase();
    const name = TICKER_NAMES[ticker] ?? '';
    const upperName = name.toUpperCase();

    let score = 0;
    if (upper === q) score = 100;
    else if (upper.startsWith(q)) score = 80;
    else if (upperName.startsWith(q)) score = 70;
    else if (upperName.includes(q)) score = 40;
    else if (upper.includes(q)) score = 30;

    if (score > 0) {
      results.push({ ticker, name: name || ticker, score });
    }
  }

  results.sort((a, b) => {
    if (b.score !== a.score) return b.score - a.score;
    return a.ticker.localeCompare(b.ticker);
  });
  return results.slice(0, limit);
}
